// Code generated by mockery 2.9.0. DO NOT EDIT.

package remotewritemock

import (
	"context"

	"github.com/cortexproject/cortex/pkg/cortexpb"
	"github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Write provides a mock function with given fields: ctx, req
func (_m *Client) Write(ctx context.Context, req *cortexpb.WriteRequest) error {
	ret := _m.Called(ctx, req)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *cortexpb.WriteRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
