// Code generated by mockery v2.10.0. DO NOT EDIT.

package influx

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockRecorder is an autogenerated mock type for the Recorder type
type MockRecorder struct {
	mock.Mock
}

// measureConversionDuration provides a mock function with given fields: user, duration
func (_m *MockRecorder) measureConversionDuration(user string, duration time.Duration) {
	_m.Called(user, duration)
}

// measureIncomingPoints provides a mock function with given fields: user, count
func (_m *MockRecorder) measureIncomingPoints(user string, count int) {
	_m.Called(user, count)
}

// measureReceivedPoints provides a mock function with given fields: user, count
func (_m *MockRecorder) measureReceivedPoints(user string, count int) {
	_m.Called(user, count)
}

// measureRejectedPoints provides a mock function with given fields: user, reason
func (_m *MockRecorder) measureRejectedPoints(user string, reason string) {
	_m.Called(user, reason)
}
