// Code generated by mockery v2.10.0. DO NOT EDIT.

package influx

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockRecorder is an autogenerated mock type for the Recorder type
type MockRecorder struct {
	mock.Mock
}

// measureConversionDuration provides a mock function with given fields: duration
func (_m *MockRecorder) measureConversionDuration(duration time.Duration) {
	_m.Called(duration)
}

// measureMetricsParsed provides a mock function with given fields: count
func (_m *MockRecorder) measureMetricsParsed(count int) {
	_m.Called(count)
}

// measureMetricsWritten provides a mock function with given fields: count
func (_m *MockRecorder) measureMetricsWritten(count int) {
	_m.Called(count)
}

// measureProxyErrors provides a mock function with given fields: reason
func (_m *MockRecorder) measureProxyErrors(reason string) {
	_m.Called(reason)
}
