---
depends_on: null
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: build
steps:
- commands:
  - DOCKER_TAG=$(bash scripts/generate-tags.sh)
  - echo -n "$${DOCKER_TAG}" > .tag
  - if test "${DRONE_SOURCE_BRANCH}" = "main"; then echo -n "$${DOCKER_TAG},latest"
    > .tags; else echo -n "$${DOCKER_TAG}" > .tags; fi
  - tail -n +1 .tags
  depends_on: []
  entrypoint: null
  environment: {}
  image: golang:1.17
  name: generate tags
  settings: {}
- commands: []
  depends_on: []
  entrypoint: null
  environment: {}
  image: plugins/gcr
  name: build + push
  settings:
    json_key:
      from_secret: gcr_admin
    registry: us.gcr.io
    repo: kubernetes-dev/influx2cortex
- commands:
  - bash ./scripts/compile-commands.sh
  depends_on: []
  entrypoint: null
  environment: {}
  image: golang:1.17
  name: build binaries
  settings: {}
- commands: []
  depends_on: []
  entrypoint: null
  environment: {}
  image: plugins/gcr
  name: 'influx2cortex: build and push'
  settings:
    build_args:
    - cmd=influx2cortex
    dockerfile: ./cmd/Dockerfile
    json_key:
      from_secret: gcr_admin
    mirror: https://mirror.gcr.io
    registry: us.gcr.io
    repo: kubernetes-dev/influx2cortex
trigger:
  branch:
  - main
  event:
    include:
    - pull_request
    - push
type: docker
---
depends_on:
- build
environment:
  DOCKERD_ROOTLESS_ROOTLESSKIT_FLAGS: -p 0.0.0.0:2376:2376/tcp
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: acceptance
services:
- command:
  - --tls=false
  - --host=tcp://0.0.0.0:2375
  - --registry-mirror=https://mirror.gcr.io
  entrypoint:
  - dockerd
  image: docker:dind
  name: docker
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run
steps:
- commands:
  - DOCKER_TAG=$(bash scripts/generate-tags.sh)
  - echo -n "$${DOCKER_TAG}" > .tag
  - if test "${DRONE_SOURCE_BRANCH}" = "main"; then echo -n "$${DOCKER_TAG},latest"
    > .tags; else echo -n "$${DOCKER_TAG}" > .tags; fi
  - tail -n +1 .tags
  depends_on: []
  entrypoint: null
  environment: {}
  image: golang:1.17
  name: generate tags
  settings: {}
- commands:
  - export ACCEPTANCE_DOCKER_TAG=$(cat .tag)
  - echo $${ACCEPTANCE_DOCKER_TAG}
  - make acceptance-tests
  depends_on: []
  entrypoint: null
  environment:
    ACCEPTANCE_CI: "true"
    ACCEPTANCE_DOCKER_AUTH_PASSWORD:
      from_secret: gcr_admin
    ACCEPTANCE_DOCKER_AUTH_USERNAME: _json_key
    ACCEPTANCE_DOCKER_HOST: docker
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  image: golang:1.17
  name: acceptance
  settings: {}
  volumes:
  - name: dockersock
    path: /var/run
trigger:
  branch:
  - main
  event:
    include:
    - pull_request
    - push
type: docker
volumes:
- name: dockersock
  temp: {}
---
depends_on:
- build
environment:
  DOCKERD_ROOTLESS_ROOTLESSKIT_FLAGS: -p 0.0.0.0:2376:2376/tcp
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: test
services:
- command:
  - --tls=false
  - --host=tcp://0.0.0.0:2375
  - --registry-mirror=https://mirror.gcr.io
  entrypoint:
  - dockerd
  image: docker:dind
  name: docker
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run
steps:
- commands:
  - DOCKER_TAG=$(bash scripts/generate-tags.sh)
  - echo -n "$${DOCKER_TAG}" > .tag
  - if test "${DRONE_SOURCE_BRANCH}" = "main"; then echo -n "$${DOCKER_TAG},latest"
    > .tags; else echo -n "$${DOCKER_TAG}" > .tags; fi
  - tail -n +1 .tags
  depends_on: []
  entrypoint: null
  environment: {}
  image: golang:1.17
  name: generate tags
  settings: {}
- commands:
  - bash ./scripts/test.sh
  depends_on: []
  entrypoint: null
  environment: {}
  image: golang:1.17
  name: test
  settings: {}
trigger:
  branch:
  - main
  event:
    include:
    - pull_request
    - push
type: docker
volumes:
- name: dockersock
  temp: {}
---
depends_on:
- build
- acceptance
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: launch influx argo workflow
steps:
- commands:
  - '[ $(git rev-parse HEAD) = $(git rev-parse remotes/origin/main) ]'
  depends_on: []
  entrypoint: null
  environment: {}
  image: golang:1.17
  name: check is latest commit
  settings: {}
- commands:
  - DOCKER_TAG=$(bash scripts/generate-tags.sh)
  - echo -n "$${DOCKER_TAG}" > .tag
  - if test "${DRONE_SOURCE_BRANCH}" = "main"; then echo -n "$${DOCKER_TAG},latest"
    > .tags; else echo -n "$${DOCKER_TAG}" > .tags; fi
  - tail -n +1 .tags
  depends_on: []
  entrypoint: null
  environment: {}
  image: golang:1.17
  name: generate tags
  settings: {}
- commands: []
  depends_on: []
  entrypoint: null
  environment: {}
  image: us.gcr.io/kubernetes-dev/drone/plugins/argo-cli
  name: launch argo workflow
  settings:
    add_ci_labels: true
    command: 'submit --from workflowtemplate/influx-deploy --name influx-deploy-$(cat
      .tag) --parameter dockertag=$(cat .tag) --parameter commit=${DRONE_COMMIT} --parameter
      commit_author=${DRONE_COMMIT_AUTHOR} --parameter commit_link=${DRONE_COMMIT_LINK} '
    namespace: influx-cd
    token:
      from_secret: argo_token
trigger:
  branch:
  - main
  event:
    include:
    - push
  paths:
    exclude:
    - .drone/**
    - .gitignore
    - README.md
type: docker
---
get:
  name: .dockerconfigjson
  path: secret/data/common/gcr
kind: secret
name: dockerconfigjson
---
get:
  name: pat
  path: infra/data/ci/github/grafanabot
kind: secret
name: gh_token
---
get:
  name: service-account
  path: infra/data/ci/gcr-admin
kind: secret
name: gcr_admin
---
get:
  name: token
  path: infra/data/ci/argo-workflows/trigger-service-account
kind: secret
name: argo_token
---
kind: signature
hmac: d06346623098a6375c4946a8443597297a1939d6d4f3bd805b00eb6a4529f199

...
