name: ci
on:
  push:
  pull_request:

jobs:
  binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Symlink Expected Path to Workspace
        run: |
          sudo mkdir -p /go/src/github.com/grafana/influx2cortex
          sudo ln -s $GITHUB_WORKSPACE/* /go/src/github.com/grafana/influx2cortex
      - name: Check current dir
        run: pwd
      - name: Build binaries
        run: $GITHUB_WORKSPACE/.github/workflows/scripts/compile-commands.sh
